"""bcrypt wrap for credential hashing (Issue #22, AC2).

Public surface
--------------

- :func:`hash_password` — bcrypt-hash a plaintext password at the
  pinned cost factor 12. Returns a ``str`` so the result can be
  persisted to SQLite TEXT without a custom adapter.
- :func:`verify_password` — constant-time compare via
  :func:`bcrypt.checkpw`. Returns ``False`` on shape mismatch
  (defensive — the gate calls this on every login attempt).

Why a dedicated module
----------------------

The existing auth gate at ``app/main.py:101-104`` inlines the bcrypt
call. Lifting it into a testable module:

1. Pins the cost factor (12) via tests rather than a code comment.
2. Centralizes input validation (``TypeError`` on non-str plaintext)
   so callers cannot accidentally store a malformed hash.
3. Keeps ``bcrypt` out of ``app/main.py`` — the gate now reads as a
   credentials-loader, not a hashing utility.
"""

from __future__ import annotations

import bcrypt

__all__ = ["hash_password", "verify_password"]

# Cost factor pinned at 12 — matches the historical inline value at
# ``app/main.py:103``. Bumping the cost factor invalidates all
# existing password hashes (each user would need to re-set their
# password). That's a deliberate operational decision, not a code
# change.
_BCRYPT_ROUNDS = 12


def hash_password(plaintext: str) -> str:
    """bcrypt-hash ``plaintext`` at the pinned cost factor.

    Returns
    -------
    str
        A bcrypt hash in the canonical ``$2b$12$...`` form. The salt
        is generated by :func:`bcrypt.gensalt` (random per call) so
        two hashes of the same plaintext differ — defending against
        hash-equality leaks in a stolen DB.

    Raises
    ------
    TypeError
        If ``plaintext`` is not a ``str``. Defense in depth — the
        Streamlit form already coerces inputs to ``str`` via the
        ``st.text_input`` widget, but the helper is safe to call from
        arbitrary call sites (admin panel, CLI seeders, tests).
    """
    if not isinstance(plaintext, str):
        raise TypeError(
            f"plaintext must be str, got {type(plaintext).__name__}"
        )
    hashed_bytes = bcrypt.hashpw(
        plaintext.encode("utf-8"),
        bcrypt.gensalt(rounds=_BCRYPT_ROUNDS),
    )
    return hashed_bytes.decode("utf-8")


def verify_password(plaintext: str, hashed: str) -> bool:
    """Constant-time compare ``plaintext`` against ``hashed``.

    Returns ``True`` iff ``plaintext`` matches the hash. Delegates to
    :func:`bcrypt.checkpw` so the compare runs in constant time on
    the hashed-byte representation — no early-exit on string
    equality, no timing oracle.

    Raises
    ------
    ValueError
        If ``hashed`` is empty or not a valid bcrypt hash. A
        malformed hash is a programmer error (e.g., a SQL NULL
        converted to ``""``), and surfacing it as ``ValueError`` is
        more actionable than the ``False``-return the auth gate
        would otherwise treat as "wrong password."
    """
    if not isinstance(hashed, str) or not hashed:
        raise ValueError("hashed must be a non-empty bcrypt hash string")
    if not isinstance(plaintext, str):
        # Defense in depth — the auth gate is the only intended caller
        # and it passes ``str`` from the form widget.
        return False
    try:
        return bcrypt.checkpw(
            plaintext.encode("utf-8"),
            hashed.encode("utf-8"),
        )
    except (ValueError, TypeError):
        # Malformed bcrypt hash (e.g., a truncated column value or a
        # non-bcrypt string). Return False rather than raising so a
        # user with a corrupted row sees "wrong password" instead of
        # a 500 from the gate.
        return False
